-- Initial schema for PDV project

create table companies (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique
);

create table tb_role (
    id bigint generated by default as identity primary key,
    name smallint not null unique,
    constraint chk_role CHECK (name between 0 and 1)
);

create table users (
    id bigint generated by default as identity primary key,
    cpf varchar(255) not null unique,
    name varchar(255) not null,
    email varchar(255) not null unique,
    password varchar(255) not null,
    company_id bigint,
    constraint fk_users_company FOREIGN KEY(company_id) REFERENCES companies(id)
);

create table products (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(1000),
    price numeric(38,2) not null,
    stock integer not null,
    company_id bigint not null,
    constraint fk_products_company FOREIGN KEY(company_id) REFERENCES companies(id)
);

create table tb_user_role (
    role_id bigint not null,
    user_id bigint not null,
    primary key (role_id, user_id),
    constraint fk_userrole_role FOREIGN KEY(role_id) REFERENCES tb_role(id),
    constraint fk_userrole_user FOREIGN KEY(user_id) REFERENCES users(id)
);

create table transactions (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    product_id bigint not null,
    price_at_purchase numeric(38,2) not null,
    quantity integer not null,
    created_at timestamp not null,
    constraint fk_transactions_user FOREIGN KEY(user_id) REFERENCES users(id),
    constraint fk_transactions_product FOREIGN KEY(product_id) REFERENCES products(id)
);

